/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaBuscar.java
 *
 * Created on 31/10/2011, 04:50:26 PM
 */

package clases;

import java.util.ArrayList;
import clases.conecbd;
import clases.ModeloTabla;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author DARK DEVIL
 */
public class VentanaBuscar extends javax.swing.JDialog {
    conecbd con;
    int col;
    String[] nom;
    ArrayList<String[]> val = new ArrayList<String[]>();
    String query;
    String des;
    int cod;
    Object[] tfParam;
    public VentanaBuscar(String consulta_sql,String[] nombre_columnas,int cantidad_columnas,Object[] objetos_pa_devolver_resultado) {
        setModal(true);
             this.query  =consulta_sql;
        this.nom = nombre_columnas;
        this.col = cantidad_columnas;
        this.tfParam = objetos_pa_devolver_resultado;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtfValorBusqueda = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jscrllDetalleBusqueda = new javax.swing.JScrollPane();
        jtblDetalleBusqueda = new javax.swing.JTable();
        jbtnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Descripcion:");

        jtxtfValorBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfValorBusquedaKeyPressed(evt);
            }
        });

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jtblDetalleBusqueda.setModel(new ModeloTabla(col, nom, val));
        jtblDetalleBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblDetalleBusquedaMouseClicked(evt);
            }
        });
        jtblDetalleBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblDetalleBusquedaKeyPressed(evt);
            }
        });
        jscrllDetalleBusqueda.setViewportView(jtblDetalleBusqueda);

        javax.swing.GroupLayout jpnlBuscarLayout = new javax.swing.GroupLayout(jpnlBuscar);
        jpnlBuscar.setLayout(jpnlBuscarLayout);
        jpnlBuscarLayout.setHorizontalGroup(
            jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBuscarLayout.createSequentialGroup()
                .addGroup(jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtfValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnBuscar))
                    .addComponent(jscrllDetalleBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlBuscarLayout.setVerticalGroup(
            jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBuscarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtfValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jscrllDetalleBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jbtnSeleccionar.setText("Cerrar");
        jbtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jbtnSeleccionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSeleccionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtfValorBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfValorBusquedaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbtnBuscar.doClick();
        }
}//GEN-LAST:event_jtxtfValorBusquedaKeyPressed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        try {
            con = new conecbd();
            con.conectar();
            boolean exito = con.busqueda(query+"upper('%"+this.jtxtfValorBusqueda.getText().toString()+"%')");
            val = new ArrayList<String[]>();
            if(exito){
                while (con.rs.next()) {
                    String[] aux = new String[col];
                    for (int i = 0; i < aux.length; i++) {
                        aux[i] = String.valueOf(con.rs.getObject(i+1));

                    }
                    val.add(aux);
                }
            }
            jtblDetalleBusqueda.setModel(new ModeloTabla(col, nom, val));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jtblDetalleBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblDetalleBusquedaMouseClicked
        for (int i = 0; i < tfParam.length; i++) {
            if(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i) != null) {
                if ( tfParam[i] instanceof JTextField ) {
                    //System.out.println(((JTextField)tfParam[i]).getName());
                    ((JTextField)tfParam[i]).setText(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
                } else if(tfParam[i] instanceof JComboBox){
                    int indice =Integer.parseInt(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
                    //System.out.print(indice);
                    ((JComboBox)tfParam[i]).setSelectedIndex(indice);
                    //DropDown itemcbo = (DropDown)((JComboBox)tfParam[i]).getItemAt(indice);
                    //System.out.println(itemcbo.getCodigo());
                }

            }
            //tfParam[i].setText(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
        }//Cierre del for
}//GEN-LAST:event_jtblDetalleBusquedaMouseClicked

    private void jtblDetalleBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblDetalleBusquedaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jbtnSeleccionar.doClick();
        }
}//GEN-LAST:event_jtblDetalleBusquedaKeyPressed

    private void jbtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarActionPerformed
        //this.setVisible(false);
        this.dispose();
}//GEN-LAST:event_jbtnSeleccionarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnSeleccionar;
    private javax.swing.JPanel jpnlBuscar;
    private javax.swing.JScrollPane jscrllDetalleBusqueda;
    private javax.swing.JTable jtblDetalleBusqueda;
    private javax.swing.JTextField jtxtfValorBusqueda;
    // End of variables declaration//GEN-END:variables

}
