/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.conecbd;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.postgresql.util.PSQLException;

/**
 *
 * @author jeferzon
 */
public class acceso extends javax.swing.JFrame {
        conecbd con;
        ResultSet rs;
         private static String codempleado="";
         
    /**
     * Creates new form Acceso
     */
    public acceso() {
        initComponents();
        con= new conecbd();
        con.conectar();
        
    }
    public static String obtenerempleado(){
return codempleado;
        
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txusuario = new javax.swing.JTextField();
        txcontraseña = new javax.swing.JPasswordField();
        btnacceptar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acceso Al Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N

        jLabel2.setText("Contraseña:");

        jLabel1.setText("Usuario:");

        txusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txusuarioKeyPressed(evt);
            }
        });

        txcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcontraseñaActionPerformed(evt);
            }
        });
        txcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txcontraseñaKeyPressed(evt);
            }
        });

        btnacceptar.setText("Aceptar");
        btnacceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacceptarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txcontraseña)
                    .addComponent(txusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnacceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnacceptar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcontraseñaActionPerformed

    private void txusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txusuarioKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            txcontraseña.requestFocus();
        }
    }//GEN-LAST:event_txusuarioKeyPressed

    private void txcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcontraseñaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
        if (!txusuario.getText().equals("")) {
                rs = con.listar_datos("select * from empleado where emp_nick = '"+txusuario.getText()+"'");
            try {
                if (rs.isBeforeFirst()) {
                    txcontraseña.setEnabled(true);
                    txcontraseña.requestFocus();
                }else {JOptionPane.showMessageDialog(null,"Usuario no existe");
                txcontraseña.getText();
               txcontraseña.requestFocus();} 
            } catch (SQLException ex) {
              Logger.getLogger(acceso.class.getName()).log(Level.SEVERE, null, ex);
          }
                
            } else {
                JOptionPane.showMessageDialog(null,"Inserte Credenciales","atencion",JOptionPane.INFORMATION_MESSAGE);
                txusuario.setText("");
                txusuario.requestFocus();
            }
              if (!txcontraseña.getText().trim().equals("")) {
                rs=con.listar_datos("select * from empleado where emp_nick='"
                        +txusuario.getText()+"'and emp_clave=md5('"+txcontraseña.getText()+"')");
                try {
                    if (rs.isBeforeFirst()) {
                        while (rs.next()) {
                          codempleado=rs.getString("emp_cod");
                        }
                        new principal().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null,"usuario o contrase;a incorrecto");
                        txcontraseña.setText("");
                        txcontraseña.requestFocus();
                        txusuario.setText("");
                        txusuario.requestFocus();
                    }
                    } catch (SQLException ex) {
                    Logger.getLogger(acceso.class.getName()).log(Level.SEVERE, null, ex);
                }
                }      
    }//GEN-LAST:event_txcontraseñaKeyPressed
}
    private void btnacceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacceptarActionPerformed
        
            if (!txusuario.getText().equals("")) {
                rs = con.listar_datos("select * from empleado where emp_nick = '"+txusuario.getText()+"'");
            try {
                if (rs.isBeforeFirst()) {
                    txcontraseña.setEnabled(true);
                    txcontraseña.requestFocus();
                }else {JOptionPane.showMessageDialog(null,"Usuario no existe");
                txcontraseña.getText();
               txcontraseña.requestFocus();} 
            } catch (SQLException ex) {
              Logger.getLogger(acceso.class.getName()).log(Level.SEVERE, null, ex);
          }
                
            } else {
                JOptionPane.showMessageDialog(null,"Inserte Credenciales","atencion",JOptionPane.INFORMATION_MESSAGE);
                txusuario.setText("");
                txusuario.requestFocus();
            }
              if (!txcontraseña.getText().trim().equals("")) {
                rs=con.listar_datos("select * from empleado where emp_nick='"
                        +txusuario.getText()+"'and emp_clave=md5('"+txcontraseña.getText()+"')");
                try {
                    if (rs.isBeforeFirst()) {
                        
                        new principal().setVisible(true);
                        new acceso().setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null,"usuario o contrase;a incorrecto");
                        txcontraseña.setText("");
                        txcontraseña.requestFocus();
                        txusuario.setText("");
                        txusuario.requestFocus();
                    }
                    } catch (SQLException ex) {
                    Logger.getLogger(acceso.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
    }//GEN-LAST:event_btnacceptarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacceptar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txcontraseña;
    private javax.swing.JTextField txusuario;
    // End of variables declaration//GEN-END:variables

    String obtenerEmpleado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
