/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.conecbd;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeferzon
 */
public class articulo extends javax.swing.JDialog {

    conecbd con;
    ResultSet rs, rs1, rs2;
    int ban = 0;

    /**
     * Creates new form articulo
     */
    public articulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = new conecbd();
        con.conectar();
        llenar_grilla();
    }

    public void habilitar(int estado) {
        switch (estado) {
            case 0:
                btnagregar.setEnabled(false);
                btneditar.setEnabled(false);
                btnborrar.setEnabled(false);
                btngrabar.setEnabled(false);
                btncancelar.setEnabled(true);
                btnsalir.setEnabled(false);
                btnimprimir.setEnabled(false);
                break;
            case 1:
                btnagregar.setEnabled(true);
                btneditar.setEnabled(true);
                btnborrar.setEnabled(true);
                btngrabar.setEnabled(false);
                btncancelar.setEnabled(false);
                btnsalir.setEnabled(true);
                btnimprimir.setEnabled(true);
                break;
        }
    }

    public void llenar_combo(String ordenacion) {
        rs1 = con.listar_datos("select (mar_cod||'-'||mar_descri) as descri "
                + "from marca order by mar_cod =" + ordenacion + " desc");
        try {
            while (rs1.next()) {
                vmar_cod.addItem(rs1.getString("descri"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void llenar_combo1(String ordenacion) {
        rs2 = con.listar_datos("select (tipo_cod||'-'||tipo_descri) as tipo "
                + "from tipo_impuesto order by tipo_cod =" + ordenacion + " desc");
        try {
            while (rs2.next()) {
                vtipo_cod.addItem(rs2.getString("tipo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void llenar_grilla(){
        String campos[] = new String[]{"CODIGO","DESCRIPCION","PRECIO V.","PRECIO C.","IMPUESTO"};
        DefaultTableModel modelo = new DefaultTableModel(null,campos);
        grilla.setModel(modelo);
        rs=con.listar_datos("select * from v_articulo order by art_cod");
        try {
            while (rs.next()) {
                String datos[]= new String[]{rs.getString("art_cod"),rs.getString("art_descri")+" "+rs.getString("mar_descri"),
                rs.getString("art_precioc"),rs.getString("art_preciov"),rs.getString("tipo_descri")};
                modelo.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vart_cod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnimprimir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vart_codbarra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vmar_cod = new javax.swing.JComboBox<>();
        vart_descri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vart_precioc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vart_preciov = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vtipo_cod = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        vart_cod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        vart_cod.setEnabled(false);
        vart_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vart_codKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("CODIGO:");

        btnimprimir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("COD. BARRA:");

        vart_codbarra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        vart_codbarra.setEnabled(false);
        vart_codbarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vart_codbarraKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("MARCA:");

        vmar_cod.setEnabled(false);
        vmar_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vmar_codKeyPressed(evt);
            }
        });

        vart_descri.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        vart_descri.setEnabled(false);
        vart_descri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vart_descriKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("DESCRIPCION:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("PRECIO COMPRA:");

        vart_precioc.setText("0");
        vart_precioc.setEnabled(false);
        vart_precioc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vart_preciocKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("PRECIO VENTA:");

        vart_preciov.setText("0");
        vart_preciov.setEnabled(false);
        vart_preciov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vart_preciovKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("IMPUESTO:");

        vtipo_cod.setEnabled(false);
        vtipo_cod.setFocusable(false);
        vtipo_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vtipo_codKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(vart_preciov, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vart_descri, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vart_precioc, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vart_codbarra, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vtipo_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vmar_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(vart_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(vart_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(vart_codbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(vmar_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(vtipo_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnimprimir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vart_descri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vart_precioc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vart_preciov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        btneditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btneditarKeyPressed(evt);
            }
        });

        btnborrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnborrar.setText("BORRAR");

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btngrabar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btngrabar.setText("GRABAR");
        btngrabar.setEnabled(false);
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaMouseClicked(evt);
            }
        });
        grilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                grillaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(grilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
  con.generarreporte("Articulos");
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        habilitar(0);
        ban = 1;
        rs = con.listar_datos("select coalesce(max(art_cod),0)+1 as ultimo from articulo");
        try {
            rs.next();
            vart_cod.setText(rs.getString("ultimo"));
            rs.close();
            llenar_combo("0");
            llenar_combo1("0");
            vart_codbarra.setEnabled(true);
            vart_codbarra.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(articulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnagregarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        habilitar(1);
        ban=0;
        vart_cod.setText("");
        vart_cod.setEnabled(false);
        vart_codbarra.setText("");
        vart_codbarra.setEnabled(false);
        vmar_cod.removeAllItems();
        vmar_cod.setEnabled(false);
        vart_descri.setText("");
        vart_descri.setEnabled(false);
        vart_precioc.setText("");
        vart_precioc.setEnabled(false);
        vart_preciov.setText("");
        vart_preciov.setEnabled(false);        
        vtipo_cod.removeAllItems();
        vtipo_cod.setEnabled(false);
        llenar_grilla();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void vart_codbarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vart_codbarraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vart_codbarra.getText().trim().equals("")) {
                vmar_cod.setEnabled(true);
                vmar_cod.requestFocus();
            btngrabar.setEnabled(true);
            
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vart_codbarra.setText("");
                vart_codbarra.requestFocus();
            }
        }
    }//GEN-LAST:event_vart_codbarraKeyPressed

    private void vmar_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vmar_codKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                vtipo_cod.setEnabled(true);
                vtipo_cod.requestFocus();
            
       }          
    }//GEN-LAST:event_vmar_codKeyPressed

    private void vart_descriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vart_descriKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vart_descri.getText().trim().equals("")) {
                vart_precioc.setEnabled(true);
                vart_precioc.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vart_descri.setText("");
                vart_descri.requestFocus();
            }
        }
    }//GEN-LAST:event_vart_descriKeyPressed

    private void vart_preciocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vart_preciocKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vart_precioc.getText().trim().equals("")) {
                if (Integer.parseInt(vart_precioc.getText().trim()) >= 0) {
                    vart_preciov.setEnabled(true);
                    vart_preciov.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor o igual a cero", "Atención", JOptionPane.INFORMATION_MESSAGE);
                    vart_precioc.setText("");
                    vart_precioc.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vart_precioc.setText("");
                vart_precioc.requestFocus();
            }
        }
    }//GEN-LAST:event_vart_preciocKeyPressed

    private void vart_preciovKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vart_preciovKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vart_preciov.getText().trim().equals("")) {
                if (Integer.parseInt(vart_preciov.getText().trim()) >= 0) {
                    if (Integer.parseInt(vart_preciov.getText().trim())
                            >= Integer.parseInt(vart_precioc.getText().trim())) {
                        vtipo_cod.setEnabled(true);
                        btngrabar.setEnabled(true);
                        btngrabar.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "El precio de venta debe ser mayor o igual al de compra", "Atención", JOptionPane.INFORMATION_MESSAGE);
                        vart_preciov.setText("");
                        vart_preciov.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor o igual a cero", "Atención", JOptionPane.INFORMATION_MESSAGE);
                    vart_preciov.setText("");
                    vart_preciov.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vart_preciov.setText("");
                vart_preciov.requestFocus();
            }
        }
    }//GEN-LAST:event_vart_preciovKeyPressed

    private void vtipo_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vtipo_codKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
           vart_descri.setEnabled(true);
                           vart_descri.requestFocus();
        }
    }//GEN-LAST:event_vtipo_codKeyPressed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(null,"Desea grabar los datos del articulo?","Atención",JOptionPane.YES_NO_OPTION);
        if (mensaje==JOptionPane.YES_OPTION) {
            if (ban==1) {
                con.insertar_datos("articulo", "art_cod, art_codbarra, mar_cod, art_descri, art_precioc, art_preciov, tipo_cod",
               vart_cod.getText()+",'"+vart_codbarra.getText()+"',split_part('"+vmar_cod.getSelectedItem()
               +"','-',1)::integer,'"+vart_descri.getText()+"',"+vart_precioc.getText()+","+vart_preciov.getText()
               +",split_part('"+vtipo_cod.getSelectedItem()+"','-',1)::integer", 0);
                btncancelar.doClick();
            }
            
            if (ban == 2) {//accion editar
                con.actualizar_datos("articulo","art_codbarra="+vart_codbarra.getText()
                        +",mar_cod=split_part('"+vmar_cod.getSelectedItem()+"','-',1)::integer,art_descri='"+vart_descri.getText()
                       
                    +"',art_precioc="+vart_precioc.getText()+",art_preciov="
                        +vart_preciov.getText()+",tipo_cod=split_part('"+vtipo_cod.getSelectedItem()+"','-',1)::integer","art_cod="+vart_cod.getText());
                   
                btncancelar.doClick();
            }
        } else {
            btncancelar.doClick();
        }
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
    dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
              habilitar(0);
        ban = 2;//editar
        vart_cod.setEnabled(true);
        vart_cod.requestFocus();
    
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btneditarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarKeyPressed

    private void vart_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vart_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vart_cod.getText().trim().equals("")) {
                if (Integer.parseInt(vart_cod.getText().trim()) > 0) {
                    rs = con.listar_datos("select * from articulo where art_cod =" + vart_cod.getText());
                    try {
                        if (rs.isBeforeFirst()) {
                            rs.next();
                            vart_codbarra.setText(rs.getString("art_codbarra"));
                            llenar_combo(rs.getString("mar_cod"));
                            llenar_combo1(rs.getString("tipo_cod"));
                            vart_descri.setText(rs.getString("art_descri"));
                            
                            vart_precioc.setText(rs.getString("art_precioc"));
                            vart_preciov.setText(rs.getString("art_preciov"));
                           vart_descri.setEnabled(true);
                           vart_descri.requestFocus();
                           vart_precioc.setEnabled(true);
                            vart_preciov.setEnabled(true);
                            vtipo_cod.setEnabled(true);
                            vmar_cod.setEnabled(true);
                          
                            
                    
                            if (ban == 3) {
                                int mensaje = JOptionPane.showConfirmDialog(null, "Desea borrar los datos del cliente?",
                                        "Atención", JOptionPane.YES_NO_OPTION);
                                if (mensaje == 0) {
                                    con.BorrarDatos("articulo", "art_cod", vart_cod.getText());
                                    btncancelar.doClick();
                                } else {
                                    btncancelar.doClick();
                                }
                            } else {
                                vart_codbarra.setEnabled(true);
                                vart_codbarra.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontraron datos coincidentes", "Atención", JOptionPane.INFORMATION_MESSAGE);
                            vart_cod.setText("");
                           vart_cod.requestFocus();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Graficos.articulo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero", "Atención", JOptionPane.INFORMATION_MESSAGE);
                    vart_cod.setText("");
                    vart_cod.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vart_cod.setText("");
                vart_cod.requestFocus();
            }
        }
    }                                  

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        habilitar(0);
        ban = 3;
        vart_cod.setEnabled(true);
        vart_cod.requestFocus();
    }                                         

    private void art_codActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void art_descripcionKeyPressed(java.awt.event.KeyEvent evt) {                                           
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vart_codbarra.getText().trim().equals("")) {
                btngrabar.setEnabled(true);
                vart_descri.setEnabled(true);
                vart_descri.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vart_descri.setText("");
                vart_descri.requestFocus();
            }
        }
    }//GEN-LAST:event_vart_codKeyPressed

    private void grillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseClicked
       
    }//GEN-LAST:event_grillaMouseClicked

    private void grillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grillaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_grillaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                articulo dialog = new articulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField vart_cod;
    private javax.swing.JTextField vart_codbarra;
    private javax.swing.JTextField vart_descri;
    private javax.swing.JTextField vart_precioc;
    private javax.swing.JTextField vart_preciov;
    private javax.swing.JComboBox<String> vmar_cod;
    private javax.swing.JComboBox<String> vtipo_cod;
    // End of variables declaration//GEN-END:variables
}
