/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.conectbd;
import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jeferzon
 */
public class cambiar_clave extends javax.swing.JDialog {
    conectbd con;
    ResultSet rs1, rs2;
    String cod_emp ="";
    /**
     * Creates new form cambiar_clave
     */
    public cambiar_clave(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = new conectbd();
        con.conectar();
        cod_emp = new acceso().obtenerEmpleado();
        nombre();
    }
    public void nombre(){
        rs1 = con.listar_datos("select (emp_nombre||' '||emp_apellido) as nombres"
                + " from empleado where emp_cod="+cod_emp);
        try {
            if (rs1.isBeforeFirst()) {
                while(rs1.next()){
                    vempleado.setText(rs1.getString("nombres"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(cambiar_clave.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clave_actual = new javax.swing.JPasswordField();
        clave_nueva = new javax.swing.JPasswordField();
        clave_nueva1 = new javax.swing.JPasswordField();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        vempleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA CAMBIAR CLAVE");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar Clave"));

        jLabel1.setText("Clave actual:");

        jLabel2.setText("Clave nueva:");

        jLabel3.setText("Repetir clave nueva:");

        clave_actual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clave_actualKeyPressed(evt);
            }
        });

        clave_nueva.setEnabled(false);
        clave_nueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clave_nuevaKeyPressed(evt);
            }
        });

        clave_nueva1.setEnabled(false);
        clave_nueva1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clave_nueva1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clave_nueva1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clave_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clave_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clave_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clave_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clave_nueva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/guardar1.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setEnabled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/exit_1.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        vempleado.setEditable(false);
        vempleado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(vempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnsalir))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clave_actualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave_actualKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(!clave_actual.getText().trim().equals("")){
                rs2 = con.listar_datos("select * from empleado "
                        + "where emp_cod="+cod_emp +"and emp_clave = "
                                + "md5('"+clave_actual.getText()+"')");
                try {
                    if (rs2.isBeforeFirst()) {
                        clave_nueva.setEnabled(true);
                        clave_nueva.requestFocus();
                    }else{
                        JOptionPane.showMessageDialog(null,"La clave actual no es correcta","Error",JOptionPane.WARNING_MESSAGE);
                        clave_actual.setText("");
                        clave_actual.requestFocus();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(cambiar_clave.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Este campo no puede estar vacio","Atencion",JOptionPane.INFORMATION_MESSAGE);
                clave_actual.setText("");
                clave_actual.requestFocus();
            }
        }
    }//GEN-LAST:event_clave_actualKeyPressed

    private void clave_nuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave_nuevaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (!clave_nueva.getText().trim().equals("")) {
                clave_nueva1.setEnabled(true);
                clave_nueva1.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null,"Este campo no puede estar vacio","Atencion",JOptionPane.INFORMATION_MESSAGE);
                clave_nueva.setText("");
                clave_nueva.requestFocus();
            }
            
        }
    }//GEN-LAST:event_clave_nuevaKeyPressed

    private void clave_nueva1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave_nueva1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (!clave_nueva1.getText().trim().equals("")) {
                if (clave_nueva1.getText().trim().equals(clave_nueva.getText().trim())) {
                    btnguardar.setEnabled(true);
                    btnguardar.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null,"Las claves no coinciden","Error",JOptionPane.WARNING_MESSAGE);
                    clave_nueva.setText("");
                    clave_nueva1.setText("");
                    clave_nueva1.setEnabled(false);
                    clave_nueva.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Este campo no puede quedar vacio","Atencion",JOptionPane.INFORMATION_MESSAGE);
                clave_nueva1.setText("");
                clave_nueva1.requestFocus();
            }
            
        }
    }//GEN-LAST:event_clave_nueva1KeyPressed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        int cambiar = JOptionPane.showConfirmDialog(null, "Desea Cambiar la clave?","Atencion",JOptionPane.YES_NO_OPTION);
        if (cambiar == 0) {
            con.actualizar_datos("empleado", "emp_clave=md5('"+clave_nueva1.getText()+"')", "emp_cod="+cod_emp);
            clave_actual.setText("");
            clave_nueva.setText("");
            clave_nueva.setEnabled(false);
            clave_nueva1.setText("");
            clave_nueva1.setEnabled(false);
            btnguardar.setEnabled(false);
            btnsalir.requestFocus();
            
        }else{
            clave_actual.setText("");
            clave_actual.requestFocus();
            clave_nueva.setText("");
            clave_nueva.setEnabled(false);
            clave_nueva1.setText("");
            clave_nueva1.setEnabled(false);
            btnguardar.setEnabled(false);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiar_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiar_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiar_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiar_clave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cambiar_clave dialog = new cambiar_clave(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPasswordField clave_actual;
    private javax.swing.JPasswordField clave_nueva;
    private javax.swing.JPasswordField clave_nueva1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField vempleado;
    // End of variables declaration//GEN-END:variables
}
