/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.VentanaBuscar;
import clases.conecbd;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeferzon
 */
public class compras extends javax.swing.JDialog {
conecbd con;
    ResultSet rs, rs1, rs2, rs3;
    int ban = 0;
    String empleado = "", subtotal = "0";
    SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
    String strfecha = "";
    Date fecha;
    private Object prv_plazo;
    private JTextField pcompras;
    private Object total_compras;
    private Object prv_cod;
    /**
     * Creates new form compras
     */
    public compras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = new conecbd();
        con.conectar();
        empleado = "1";
        //empleado = acceso.obtenerEmpleado();
        String campos[] = new String[]{"Codigo", "Descripción", "Cantidad", "Precio", "Subtotal", "Deposito"};
        DefaultTableModel modelo = new DefaultTableModel(null, campos);
        grilla.setModel(modelo);
        prv_cod.setVisible(false);
        pack ();
    }
public void habilitar(int estado) {
        switch (estado) {
            case 0:
                btnagregar.setEnabled(false);
                btnanular.setEnabled(false);
                btncancelar.setEnabled(true);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(false);
                break;
            case 1:
                btnagregar.setEnabled(true);
                btnanular.setEnabled(true);
                btncancelar.setEnabled(false);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(true);
                break;
        }
    }
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        com_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vcliente = new javax.swing.JTextField();
        prvi_cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vempleado = new javax.swing.JTextField();
        com_fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        vtipo_compra = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cpedido = new javax.swing.JComboBox<>();
        cped_cod = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vcan_cuota = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        prvi_plazo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cdep_cod = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cart_descri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ccant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ccom_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        vven_total = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btnanular = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("COMPRA N°:");

        com_cod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        com_cod.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("FECHA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("PROVEEDOR");

        vcliente.setEditable(false);
        vcliente.setOpaque(false);

        prvi_cod.setOpaque(false);
        prvi_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prvi_codKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("EMPLEADO:");

        vempleado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        vempleado.setOpaque(false);

        com_fecha.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("F3");

        vtipo_compra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTADO", "CREDITO" }));
        vtipo_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vtipo_compraKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("CONDICION:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("TIPO:");

        cpedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN PEDIDO", "CON PEDIDO" }));
        cpedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpedidoKeyPressed(evt);
            }
        });

        cped_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cped_codKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("INTERVALO:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("N° PEDIDO:");

        vcan_cuota.setText("1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("CANT. CUOTAS:");

        prvi_plazo.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vempleado)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(prvi_cod)
                            .addComponent(cpedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(com_cod, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cped_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vcan_cuota, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prvi_plazo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vcliente)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(com_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vtipo_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(com_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(com_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vtipo_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(vcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(prvi_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(cped_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(vcan_cuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(prvi_plazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cdep_cod.setOpaque(false);
        cdep_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cdep_codKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("DEPOSITO");

        cart_descri.setOpaque(false);
        cart_descri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cart_descriKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("ARTICULO");

        ccant.setOpaque(false);
        ccant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ccantKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("CANTIDAD");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("PRECIO");

        ccom_precio.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdep_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cart_descri, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ccant, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ccom_precio)
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdep_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cart_descri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccom_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(grilla);

        vven_total.setEditable(false);
        vven_total.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        vven_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vven_total.setText("0");
        vven_total.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/nuevo1.png"))); // NOI18N
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnanular.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnanular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/borrar1.png"))); // NOI18N
        btnanular.setText("ANULAR");
        btnanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanularActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/cancelar1.png"))); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btngrabar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/guardar1.png"))); // NOI18N
        btngrabar.setText("GRABAR");
        btngrabar.setEnabled(false);
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Home1.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnanular, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnanular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vven_total, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vven_total)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void llenar_combo() {
        rs = con.listar_datos("select (dep_cod||'-'||dep_descri) as dep from deposito");
        try {
            while (rs.next()) {
                cdep_cod.addItem(rs.getString("dep"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void prvi_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prvi_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            JTextField[] resul = new JTextField[3];
            resul[0] = this.prvi_cod;
            resul[1] = this.pcompras;

            VentanaBuscar buscompras = new VentanaBuscar("select emp_cod,prv_cod,"
                + "(com_fecha ||' '||tipo_compra) as proveedor,prv_cod,prv_ruc "
                + "from proveedor where (prv_cod||prv_ruc||prv_razonsocial) ilike ",
                new String[]{"CODIGO", "RUC", "RAZON SOCIAL", "DIRECCION", "TELEFONO"}, 5, resul);
            buscompras.setTitle("Buscador de PROVEEDOR");
            buscompras.setVisible(true);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!prvi_cod.getText().equals("")) {
                cpedido.setEnabled(true);
                cpedido.requestFocus();
            } else {
                pproveedor.setText("Seleccione con la tecla F3 proveedor para continuar...");
                prvi_cod.setText("");
                prvi_cod.requestFocus();
            }
        }
    }//GEN-LAST:event_prvi_codKeyPressed

    private void vtipo_compraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vtipo_compraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            prvi_cod.setEnabled(true);
            prvi_cod.requestFocus();
        }
    }//GEN-LAST:event_vtipo_compraKeyPressed

    private void cpedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpedidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cpedido.getSelectedItem().toString().equals("SIN PEDIDO")) {
                if (vtipo_compra.getSelectedItem().toString().equals("CONTADO")) {
                    vcan_cuota.setText("1");
                    vcan_cuota.setEnabled(false);
                    prvi_plazo_plazo.setText();
                    prvi_plazo_plazo.setEnabled(false);
                    cdep_cod.setEnabled(true);
                    cdep_cod.requestFocus();
                } else {
                    vcan_cuota.setEnabled(true);
                    vcan_cuota.requestFocus();
                }
                cped_cod.setEnabled(false);
                cped_cod.setText("");
            } else {
                if (vtipo_compra.getSelectedItem().toString().equals("CONTADO")) {
                    vcan_cuota.setText("1");
                    vcan_cuota.setEnabled(false);
                    prvi_plazo_plazo.setText();
                    prvi_plazo_plazo.setEnabled(false);
                } else {
                    vcan_cuota.setEnabled(true);
                }
                cped_cod.setEnabled(true);
                cped_cod.requestFocus();
            }
        }
    }//GEN-LAST:event_cpedidoKeyPressed

    private void cped_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cped_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            JTextField[] valores = new JTextField[3];

            valores[0] = this.cped_cod;

            VentanaBuscar busped = new VentanaBuscar("select ped_cod,ped_fecha,cliente,total "
                + "from vped_cab where cli_cod =" + prvi_cod.getText() + " and estado = 'PENDIENTE' "
                + "and (ped_cod||''||cli_cod||ped_fecha) ilike ", new String[]{"CODIGO", "FECHA", "COMPRA", "TOTAL"},
                4, valores);
            busped.setTitle("Buscar Pedidos de Clientes");
            busped.setVisible(true);

        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            /*llenar_pedido*/
        }
    }//GEN-LAST:event_cped_codKeyPressed

    private void cdep_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdep_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            com_cod.setEnabled(true);
            com_cod.requestFocus();
        }
    }//GEN-LAST:event_cdep_codKeyPressed

    private void cart_descriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cart_descriKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            JTextField[] resul = new JTextField[3];

            resul[0] = this.cart_descri;
            resul[1] = this.cart_descri;
            resul[2] = this.ccom_precio;

            VentanaBuscar busart = new VentanaBuscar("select a.com_cod,(b.prv_cod||' '||c.mar_descri)as marca,"
                + "b.art_ccom_precio,a.stoc_cant "
                + "from stock a "
                + "join articulo b on a.art_cod = b.art_cod "
                + "join marca c on b.mar_cod = c.com_cod "
                + "and dep_cod = split_part('" + cdep_cod.getSelectedItem() + "','-',1)::integer and (a.art_cod||b.pvr_cod||c.mar_descri) ilike ",
                new String[]{"CODIGO", "DESCRIPCION", "PRECIO compra", "EXISTENCIA"}, 4, resul);
            busart.setTitle("Buscador compra");
            busart.setVisible(true);

        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!cart_descri.getText().trim().equals("")) {
                ccant.setEnabled(true);
                ccant.requestFocus();
            } else {
                cart_descri.setText("Seleccione con la tecla F3 un articulo para continuar");
                cart_descri.selectAll();
                cart_descri.requestFocus();
            }
        }
    }//GEN-LAST:event_cart_descriKeyPressed

    private void ccantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccantKeyPressed
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) grilla.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!ccant.getText().trim().equals("")) {
                if (Integer.parseInt(ccant.getText().trim()) > 0) {
                    rs2 = con.listar_datos("select * from c_articulo where cart_cod=" + cart_cod.getText());
                    try {
                        if (rs2.isBeforeFirst()) {
                            if (grilla.getRowCount() == 0) {
                                //esta vacio
                                rs2.next();
                                String[] datosdetalle = new String[]{rs2.getString("cart_cod"),
                                    rs2.getString("cart_descri") + " " + rs2.getString("mar_descri"),
                                    ccant.getText(), rs2.getString("ccom_precio"),
                                    String.valueOf(Integer.parseInt(ccant.getText())
                                        * Integer.parseInt(rs2.getString("ccom_precio"))),
                                    cdep_cod.getSelectedItem().toString()};
                                modelo.addRow(datosdetalle);
                                rs2.close();
                                /*total_compras*/ 
                            } else {
                                //validar si existe el detalle
                                int lugar = 0;
                                String valor = "";
                                boolean encontro = false;
                                for (int i = 0; i < grilla.getRowCount(); i++) {
                                    if (cart_cod.getText().trim().equals(grilla.getValueAt(i, 0))
                                        && cdep_cod.getSelectedItem().toString().equals(grilla.getValueAt(i, 5))) {
                                        lugar = i;
                                        valor = String.valueOf(grilla.getValueAt(i, 2));
                                        encontro = true;
                                    }
                                }
                                if (encontro) {
                                    modelo.removeRow(lugar);
                                    rs2.next();
                                    String[] datosdetalle = new String[]{rs2.getString("art_cod"),
                                        rs2.getString("art_descri") + " " + rs2.getString("mar_descri"),
                                        String.valueOf(Integer.parseInt(ccant.getText()) + Integer.parseInt(valor)),
                                        rs2.getString("art_preciov"),
                                        String.valueOf(Integer.parseInt(ccant.getText())
                                            * Integer.parseInt(rs2.getString("art_preciov"))),
                                        cdep_cod.getSelectedItem().toString()};
                                    modelo.addRow(datosdetalle);
                                    rs2.close();
                                    /*total_compras*/
                                } else {
                                    rs2.next();
                                    String[] datosdetalle = new String[]{rs2.getString("art_cod"),
                                        rs2.getString("art_descri") + " " + rs2.getString("mar_descri"),
                                        ccant.getText(), rs2.getString("art_preciov"),
                                        String.valueOf(Integer.parseInt(ccant.getText())
                                            * Integer.parseInt(rs2.getString("art_preciov"))),
                                        cdep_cod.getSelectedItem().toString()};
                                    modelo.addRow(datosdetalle);
                                    rs2.close();
                                    /*total_compras*/
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontraron registros coincidentes", "Atención", JOptionPane.INFORMATION_MESSAGE);
                            ccant.setText("");
                            ccant.requestFocus();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero", "Atención", JOptionPane.INFORMATION_MESSAGE);
                    ccant.setText("");
                    ccant.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                ccant.setText("");
                ccant.requestFocus();
            }
            cart_descri.setText("");
            cart_cod.setText("");
            ccant.setText("");
            ccom_precio.setText("");
            cdep_cod.requestFocus();
        }
    }//GEN-LAST:event_ccantKeyPressed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        habilitar(0);
        ban = 1;//agregar
        llenar_combo();
        rs1 = con.listar_datos("select coalesce(max(prv_cod),0)+1 as ultimo,"
            + "current_date as fecha from proveedor");
        rs2 = con.listar_datos("select (prv_cod||' '||prv_ruc) as nombres "
            + "from proveedor where prv_cod=" + empleado);
        try {
            if (rs1.isBeforeFirst()) {
                rs1.next();
                com_cod.setText(rs1.getString("ultimo"));
                strfecha = rs1.getString("fecha");
                fecha = formatofecha.parse(strfecha);
                com_fecha.setDate(fecha);
                rs1.close();
                rs2.next();
                proveedor.setText(rs2.getString("nombres"));
                rs2.close();
                ctipo_compra.setEnabled(true);
                ctipo_compra.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanularActionPerformed
        dispose();
        new gestion_compras(null, false).setVisible(true);
    }//GEN-LAST:event_btnanularActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        habilitar(1);
        ban = 0;
        com_cod.setText("");
        com_cod.setEnabled(false);
        prvi_cod.setText("");
        prvi_cod.setEnabled(false);
        vempleado.setText("");
        vempleado.setEnabled(false);
        cdep_cod.removeAllItems();
        cdep_cod.setEnabled(false);
        cart_descri.setText("");
        cart_descri.setEnabled(false);
        cart_descri.setText("");
        cart_descri.setEnabled(false);
        ccant.setText("");
        ccant.setEnabled(false);
        vven_total.setText("0");
        for (int i = grilla.getRowCount() - 1; i >= 0; i--) {
            DefaultTableModel modelo;
            modelo = (DefaultTableModel) grilla.getModel();
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea grabar la compra?", "Atención", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            if (ban == 1) {
                con.insertar_datos("compras", "ccom_cod, emp_cod, pvri_cod, com_fecha, tipo_compra, can_cuota, prv_plazo, ccom_total, ccom_estado",
                    com_cod.getText() + "," + empleado + "," + prvi_cod.getText() + ",'" + con.obtener_fecha(com_fecha.getDate()) + "','"
                    + ctipo_compra.getSelectedItem() + "'," + vcan_cuota.getText() + "," + prv_plazo.toString()
                    + "," + ccom_cod.getText() + ",'P'", 0);
                for (int i = 0; i < grilla.getRowCount(); i++) {
                    con.insertar_datos("detalle_ventas", "ven_cod, dep_cod, art_cod, ven_cant, ven_precio, exenta, iva_5, iva_10",
                        com_cod.getText() + ",split_part('" + grilla.getValueAt(i, 5) + "','-',1)::integer,"
                        + grilla.getValueAt(i, 0) + "," + grilla.getValueAt(i, 2) + "," + grilla.getValueAt(i, 3) + ",0,0,0", 1);
                }
                if (cpedido.getSelectedItem().toString().equals("CON PEDIDO")) {
                    if (!cped_cod.getText().trim().equals("")) {
                        con.insertar_datos("pedido_compra", "ped_cod,com_cod,obs_pedido", cped_cod.getText()
                            +","+com_cod.getText()+",''", 1);
                    }
                }

                btncancelar.doClick();
            }
        } else {
            btncancelar.doClick();
        }
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose ();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                compras dialog = new compras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnanular;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTextField cart_descri;
    private javax.swing.JTextField ccant;
    private javax.swing.JTextField ccom_precio;
    private javax.swing.JComboBox<String> cdep_cod;
    private javax.swing.JTextField com_cod;
    private com.toedter.calendar.JDateChooser com_fecha;
    private javax.swing.JTextField cped_cod;
    private javax.swing.JComboBox<String> cpedido;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prvi_cod;
    private javax.swing.JTextField prvi_plazo;
    private javax.swing.JTextField vcan_cuota;
    private javax.swing.JTextField vcliente;
    private javax.swing.JTextField vempleado;
    private javax.swing.JComboBox<String> vtipo_compra;
    private javax.swing.JTextField vven_total;
    // End of variables declaration//GEN-END:variables

    private static class pproveedor {

        private static void setText(String seleccione_con_la_tecla_F3_un_cliente_par) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public pproveedor() {
        }
    }

    private static class gestion_compras {

        public gestion_compras(Object object, boolean b) {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
