/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Formularios.*;
import clases.conecbd;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jeferzon
 */
public class empleado extends javax.swing.JDialog {

    conecbd con;
    ResultSet rs, rs1, rs2;
    int ban = 0;

    /**
     * Creates new form marca
     */
    public empleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = new conecbd();
        con.conectar();
        pack();
        llenar_grilla();
    }

    public void habilitar(int estado) {
        switch (estado) {
            case 0://deshabilitar los botones
                btnagregar.setEnabled(false);
                btneditar.setEnabled(false);
                btnborrar.setEnabled(false);
                btncancelar.setEnabled(true);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(false);
                btnimprimir.setEnabled(false);
                break;
            case 1: //habilitar los botones
                btnagregar.setEnabled(true);
                btneditar.setEnabled(true);
                btnborrar.setEnabled(true);
                btncancelar.setEnabled(false);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(true);
                btnimprimir.setEnabled(true);
                break;
        }
    }

    public void llenar_grilla() {
        String campos[] = new String[]{"CODIGO", "CARGO","NOMBRE"," APELLIDO"};
        DefaultTableModel modelo = new DefaultTableModel(null, campos);
        grilla.setModel(modelo);
        rs1 = con.listar_datos("select * from empleado order by emp_cod");
        try {
            while (rs1.next()) {
                String datos[] = new String[]{rs1.getString("emp_cod"), rs1.getString("car_cod"),
                rs1.getString("emp_nombre"),rs1.getString("emp_apellido")};
                modelo.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vcli_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vcli_ruc = new javax.swing.JTextField();
        btnimprimir = new javax.swing.JButton();
        vcli_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vcli_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vcli_direccion = new javax.swing.JTextField();
        vcli_tel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emp_contra = new javax.swing.JPasswordField();
        em_nick = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana de Marca");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPLEADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("CODIGO:");

        vcli_cod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        vcli_cod.setEnabled(false);
        vcli_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcli_codActionPerformed(evt);
            }
        });
        vcli_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_codKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("CARGO:");

        vcli_ruc.setEnabled(false);
        vcli_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_rucKeyPressed(evt);
            }
        });

        btnimprimir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        vcli_nombre.setEnabled(false);
        vcli_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_nombreKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("APELLIDO:");

        vcli_apellido.setEnabled(false);
        vcli_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_apellidoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("DIRECCION:");

        vcli_direccion.setEnabled(false);
        vcli_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_direccionKeyPressed(evt);
            }
        });

        vcli_tel.setEnabled(false);
        vcli_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_telKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("TELEFONO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("NICK:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("CONTRASEÑA:");

        emp_contra.setEnabled(false);
        emp_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp_contraKeyPressed(evt);
            }
        });

        em_nick.setEnabled(false);
        em_nick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                em_nickKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vcli_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vcli_apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vcli_direccion)
                                    .addComponent(vcli_nombre))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vcli_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vcli_tel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(em_nick))
                                .addGap(12, 12, 12))
                            .addComponent(emp_contra))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vcli_cod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnimprimir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(vcli_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vcli_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vcli_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vcli_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vcli_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(em_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emp_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnborrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnborrar.setText("BORRAR");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btngrabar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btngrabar.setText("GRABAR");
        btngrabar.setEnabled(false);
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Ruc", " Nombre", "Apellido", "Direccion", "Email", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(grilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        habilitar(0);//llamo al metodo para deshabilitar los botones
        ban = 1;//agregar
        rs = con.listar_datos("select coalesce(max(emp_cod),0)+1 as ultimo from empleado");
        try {
            rs.next();
            vcli_cod.setText(rs.getString("ultimo"));
            rs.close();
            vcli_ruc.setEnabled(true);
            vcli_ruc.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        habilitar(1);
        ban = 0;
        vcli_cod.setText("");
        vcli_cod.setEnabled(false);
        vcli_ruc.setText("");
        vcli_ruc.setEnabled(false);
        vcli_nombre.setText("");
        vcli_nombre.setEnabled(false);
        vcli_apellido.setText("");
        vcli_apellido.setEnabled(false);
        vcli_direccion.setText("");
        vcli_direccion.setEnabled(false);        
        em_nick.setText("");
        em_nick.setEnabled(false);          
        vcli_tel.setText("");
        vcli_tel.setEnabled(false);   
        emp_contra.setText("");
        emp_contra.setEnabled(false);
        llenar_grilla();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void vcli_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_rucKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vcli_ruc.getText().trim().equals("")) {
                if (Integer.parseInt(vcli_ruc.getText()) > 0) {
                    vcli_nombre.setEnabled(true);
                    vcli_nombre.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero", "Atención", JOptionPane.INFORMATION_MESSAGE);
                    vcli_ruc.setText("");
                    vcli_ruc.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vcli_ruc.setText("");
                vcli_ruc.requestFocus();
            }
        }
    }//GEN-LAST:event_vcli_rucKeyPressed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea grabar los datos de la cliente?", "Atención", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            if (ban == 1) { //es agregar la accion
                con.insertar_datos("empleado", "emp_cod, car_cod, emp_nombre, emp_apellido, emp_direcc, emp_tel,emp_nick,emp_clave",
                         vcli_cod.getText() + "," + vcli_ruc.getText() + ",'" + vcli_nombre.getText()
                        + "','" + vcli_apellido.getText() + "','" + vcli_direccion.getText()+"','" + vcli_tel.getText() + "','"
                                 +em_nick.getText()+"',md5('"+emp_contra.getText()+"')", 0);
                btncancelar.doClick();
            }
            if (ban == 2) {//accion editar
                con.actualizar_datos("empleado","car_cod="+vcli_ruc.getText()
                        +",emp_nombre='"+vcli_nombre.getText()+"',emp_apellido='"+vcli_apellido.getText()
                        +"',emp_direcc='"+vcli_direccion.getText()+"',emp_tel='"
                        +vcli_tel.getText()+"',emp_nick='"+em_nick.getText()+"'", "emp_clave="+"md5('"+emp_contra.getText()+"')");
                btncancelar.doClick();
            }
        } else {
            btncancelar.doClick();
        }

    }//GEN-LAST:event_btngrabarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        habilitar(0);
        ban = 2;//editar
        vcli_cod.setEnabled(true);
        vcli_cod.requestFocus();
    }//GEN-LAST:event_btneditarActionPerformed

    private void vcli_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vcli_cod.getText().trim().equals("")) {
                if (Integer.parseInt(vcli_cod.getText().trim()) > 0) {
                    rs2 = con.listar_datos("select * from empleado where emp_cod =" + vcli_cod.getText());
                    try {
                        if (rs2.isBeforeFirst()) {
                            rs2.next();
                            vcli_ruc.setText(rs2.getString("car_cod"));
                            vcli_nombre.setText(rs2.getString("emp_nombre"));
                            vcli_apellido.setText(rs2.getString("emp_apellido"));
                            vcli_direccion.setText(rs2.getString("emp_direcc"));
                            em_nick.setText(rs2.getString("emp_nick"));
                            emp_contra.setText("emp_clave");
                            
                            vcli_tel.setText(rs2.getString("emp_tel"));
                            
                            if (ban == 3) {
                                int mensaje = JOptionPane.showConfirmDialog(null, "Desea borrar los datos del cliente?",
                                        "Atención", JOptionPane.YES_NO_OPTION);
                                if (mensaje == 0) {
                                    con.BorrarDatos("empleado", "car_cod", vcli_cod.getText());
                                    btncancelar.doClick();
                                } else {
                                    btncancelar.doClick();
                                }
                            } else {
                                vcli_ruc.setEnabled(true);
                                vcli_ruc.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontraron datos coincidentes", "Atención", JOptionPane.INFORMATION_MESSAGE);
                            vcli_cod.setText("");
                            vcli_cod.requestFocus();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(empleado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero", "Atención", JOptionPane.INFORMATION_MESSAGE);
                    vcli_cod.setText("");
                    vcli_cod.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vcli_cod.setText("");
                vcli_cod.requestFocus();
            }
        }
    }//GEN-LAST:event_vcli_codKeyPressed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        habilitar(0);
        ban = 3;
        vcli_cod.setEnabled(true);
        vcli_cod.requestFocus();
    }//GEN-LAST:event_btnborrarActionPerformed

    private void vcli_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcli_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcli_codActionPerformed

    private void vcli_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_nombreKeyPressed
       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vcli_nombre.getText().trim().equals("")) {
                vcli_apellido.setEnabled(true);
                vcli_apellido.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vcli_nombre.setText("");
                vcli_nombre.requestFocus();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_vcli_nombreKeyPressed

    private void vcli_apellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_apellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vcli_apellido.getText().trim().equals("")) {
                btngrabar.setEnabled(true);
                vcli_direccion.setEnabled(true);
                vcli_direccion.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atención", JOptionPane.INFORMATION_MESSAGE);
                vcli_apellido.setText("");
                vcli_apellido.requestFocus();
            }
        }
    }//GEN-LAST:event_vcli_apellidoKeyPressed

    private void vcli_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_direccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            vcli_tel.setEnabled(true);
            vcli_tel.requestFocus();
        }
    }//GEN-LAST:event_vcli_direccionKeyPressed

    private void vcli_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_telKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            em_nick.setEnabled(true);
            em_nick.requestFocus();
        }
        
             // TODO add your handling code here:
    }//GEN-LAST:event_vcli_telKeyPressed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
       con.generarreporte("Empleados");
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void em_nickKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_em_nickKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emp_contra.setEnabled(true);
           emp_contra.requestFocus();
        }
    }//GEN-LAST:event_em_nickKeyPressed

    private void emp_contraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_contraKeyPressed

 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btngrabar.requestFocus();
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_contraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                empleado dialog = new empleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTextField em_nick;
    private javax.swing.JPasswordField emp_contra;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField vcli_apellido;
    private javax.swing.JTextField vcli_cod;
    private javax.swing.JTextField vcli_direccion;
    private javax.swing.JTextField vcli_nombre;
    private javax.swing.JTextField vcli_ruc;
    private javax.swing.JTextField vcli_tel;
    // End of variables declaration//GEN-END:variables
}
