/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Lp2;
import clases.VentanaBuscar;
import clases.conectbd;
import java.awt.event.KeyEvent;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeferzon
 */
public class pedidoventas extends javax.swing.JDialog {

    conectbd con;
    ResultSet rs, rs1, rs2, rs3, rs4;
    int ban = 0;
    String empleado = "", fecha_pedido = "", subtotal = "0";
    SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
    String strfecha = "";
    Date fecha;

    /**
     * Creates new form pedidoventas
     */
    public void obtener_fecha() {
        Calendar cal = Calendar.getInstance();
        cal.setTime(vped_fecha.getDate());
        int dia = cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH) + 1;
        String sDia = "";
        String sMes = "";
        if (dia < 10) {
            sDia = "0";
        }
        sDia += dia;
        if (mes < 10) {
            sMes = "0";
        }
        sMes += mes;
        //String fecha1 = sDia + "/" + sMes + "/" + cal.get(Calendar.YEAR);
        fecha_pedido = cal.get(Calendar.YEAR) + "-" + sMes + "-" + sDia;

    }

    public pedidoventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pack();
        con = new conectbd();
        con.conectar();
        empleado = "6";
        //empleado = acceso.obtenerEmpleado();

        String campos[] = new String[]{"Codigo", "Descripcion", "Cantidad", "Precio", "Subtotal", "Deposito"};
        DefaultTableModel modelo = new DefaultTableModel(null, campos);
        grilla.setModel(modelo);
    }

    public void habilitar(int estado) {
        switch (estado) {
            case 0:
                btnagregar.setEnabled(false);
                btnanular.setEnabled(false);
                btncancelar.setEnabled(true);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(false);
                break;
            case 1:
                btnagregar.setEnabled(true);
                btnanular.setEnabled(true);
                btncancelar.setEnabled(false);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(true);
                break;

        }
    }

    public void llenar_combo() {
        rs = con.listar_datos("select (dep_cod||'-'||dep_descri) as dep from deposito");
        try {
            while (rs.next()) {
                vdep_cod.addItem(rs.getString("dep"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(pedidoventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void total_pedido() {
        if (grilla.getRowCount() == 0) {
            btngrabar.setEnabled(true);
            btngrabar.requestFocus();
            vtotal.setText("0");
        } else {
            for (int i = 0; i < grilla.getRowCount(); i++) {
                subtotal = String.valueOf(Integer.parseInt(subtotal)
                        + Integer.parseInt((String) grilla.getValueAt(i, 4)));
                vtotal.setText(subtotal);
                btngrabar.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vped_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vcli_cod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vempleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vcliente = new javax.swing.JTextField();
        vped_fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vdep_cod = new javax.swing.JComboBox<>();
        vart_descri = new javax.swing.JTextField();
        vart_cod = new javax.swing.JTextField();
        vcant = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btnanular = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        vtotal = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedido de Venta");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Pedido Nro:");

        vped_cod.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        vcli_cod.setEnabled(false);
        vcli_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcli_codActionPerformed(evt);
            }
        });
        vcli_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcli_codKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Empleado:");

        vempleado.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        vcliente.setEnabled(false);

        vped_fecha.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("F3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vped_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(vcli_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vped_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(vcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(vempleado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(vped_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(vped_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vcli_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Deposito");

        jLabel6.setText("Articulo");

        jLabel7.setText("Cantidad");

        vdep_cod.setEnabled(false);
        vdep_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vdep_codKeyPressed(evt);
            }
        });

        vart_descri.setEnabled(false);
        vart_descri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vart_descriKeyPressed(evt);
            }
        });

        vart_cod.setEnabled(false);

        vcant.setEnabled(false);
        vcant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vcantKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(vdep_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addComponent(vart_descri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vart_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vcant, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vart_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vart_descri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vdep_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grilla.setEnabled(false);
        jScrollPane2.setViewportView(grilla);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/File.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnanular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/borrar1.png"))); // NOI18N
        btnanular.setText("Anular");
        btnanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanularActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/cancelar1.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/guardar1.png"))); // NOI18N
        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/exit.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .addComponent(btnanular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btngrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnanular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vtotal.setEditable(false);
        vtotal.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        vtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vtotal.setText("0");
        vtotal.setToolTipText("");
        vtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(vtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vcli_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcli_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcli_codActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        habilitar(0);
        ban = 1;//Agregar
        llenar_combo();
        rs1 = con.listar_datos("select coalesce(max(ped_cod),0)+1 as ultimo, current_date as fecha from pedido_cabventa");
        rs2 = con.listar_datos("select (emp_nombre||' '||emp_apellido) as nombres from empleado where emp_cod=" + empleado);
        try {
            rs1.next();
            vped_cod.setText(rs1.getString("ultimo"));
            strfecha = rs1.getString("fecha");
            fecha = (Date) formatofecha.parse(strfecha);
            vped_fecha.setDate(fecha);
            rs1.close();
            rs2.next();
            vempleado.setText(rs2.getString("nombres"));
            rs2.close();
            vcli_cod.setEnabled(true);
            vcli_cod.requestFocus();

        } catch (SQLException ex) {
            Logger.getLogger(pedidoventas.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ParseException ex) {
            Logger.getLogger(pedidoventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void vcli_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcli_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            JTextField[] resul = new JTextField[3];
            resul[0] = this.vcli_cod;
            resul[2] = this.vcliente;

            VentanaBuscar buscliente = new VentanaBuscar("select cli_cod,cli_ci,(cli_nombre||' '||cli_apellido) as cliente,cli_telefono,cli_direcc"
                    + " from clientes where (cli_cod||cli_nombre||cli_apellido) ilike ", new String[]{"CODIGO", "CI", "NOMBRE/APELLIDO", "TELEFONO", "DIRECCION"
                        + ""}, 5, resul);

            buscliente.setTitle("Buscador de Cliente");
            buscliente.setVisible(true);
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (!vcli_cod.getText().trim().equals("")) {
                    vdep_cod.setEnabled(true);
                    vdep_cod.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio. Pulse F3 Para buscar el cliente", "Atencion", JOptionPane.WARNING_MESSAGE);
                    vcli_cod.setText("");
                    vcli_cod.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_vcli_codKeyPressed

    private void vdep_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vdep_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            vart_descri.setEnabled(true);
            vart_descri.requestFocus();

        }
    }//GEN-LAST:event_vdep_codKeyPressed

    private void vart_descriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vart_descriKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            JTextField[] resul = new JTextField[2];
            resul[0] = this.vart_cod;
            resul[1] = this.vart_descri;

            VentanaBuscar busart = new VentanaBuscar("select a.art_cod,(b.art_descri||' '||c.mar_descri) as producto,"
                    + "b.art_preciov,a.stoc_cant from stock a, articulo b, marca c "
                    + "where a.art_cod = b.art_cod and b.mar_cod = c.mar_cod "
                    + "and dep_cod = (select split_part('" + vdep_cod.getSelectedItem() + "','-',1)::integer) "
                    + "and (a.art_cod||'-'||b.art_descri||' '||c.mar_descri) like ",
                    new String[]{"CODIGO", "PRODUCTO", "PRECIO", "EXISTENCIA"}, 4, resul);

            busart.setTitle("Buscador de articulo");
            busart.setVisible(true);
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (!vart_descri.getText().trim().equals("")) {
                    vcant.setEnabled(true);
                    vcant.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio. Pulse F3 Para buscar el articulo", "Atencion", JOptionPane.WARNING_MESSAGE);
                    vart_descri.setText("");
                    vart_descri.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_vart_descriKeyPressed

    private void vcantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcantKeyPressed
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) grilla.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vcant.getText().trim().equals("")) {
                boolean sn = Lp2.esnumero(vcant.getText());
                if (sn) {
                    if (Integer.parseInt(vcant.getText().trim()) > 0) {
                        rs2 = con.listar_datos("select * from v_articulo where art_cod =" + vart_cod.getText());
                        try {
                            if (rs2.isBeforeFirst()) {
                                if (grilla.getRowCount() == 0) {
                                    //esta vacio 
                                    rs2.next();
                                    String[] datosdetalle = new String[]{rs2.getString("art_cod"), rs2.getString("art_descri") + " " + rs2.getString("mar_descri"),
                                        vcant.getText(), rs2.getString("art_preciov"),
                                        String.valueOf(Integer.parseInt(vcant.getText()) * Integer.parseInt(rs2.getString("art_preciov"))), vdep_cod.getSelectedItem().toString()};
                                    modelo.addRow(datosdetalle);
                                    rs2.close();
                                    total_pedido();
                                } else {
                                    //validar si existe el detalle
                                    int lugar = 0;
                                    String valor = "";
                                    boolean encontro = false;
                                    for (int i = 0; i < grilla.getRowCount(); i++) {
                                        if (vart_cod.getText().trim().equals(grilla.getValueAt(i, 0))
                                                && vdep_cod.getSelectedItem().toString().equals(grilla.getValueAt(i, 5))) {
                                            lugar = i;
                                            valor = String.valueOf(grilla.getValueAt(i, 2));
                                            encontro =true;
                                        }
                                    }
                                    if (encontro) {
                                       modelo.removeRow(lugar);
                                       rs2.next();
                                        String[] datosdetalle = new String[]{rs2.getString("art_cod"),
                                            rs2.getString("art_descri") + " " + rs2.getString("mar_descri"),
                                            String.valueOf(Integer.parseInt(vcant.getText())+ Integer.parseInt(valor))
                                                , rs2.getString("art_preciov"),
                                            String.valueOf(Integer.parseInt(vcant.getText()) 
                                            * Integer.parseInt(rs2.getString("art_preciov"))),
                                            vdep_cod.getSelectedItem().toString()};
                                        modelo.addRow(datosdetalle);
                                        rs2.close();
                                        total_pedido(); 
                                    } else {
                                        rs2.next();
                                        String[] datosdetalle = new String[]{rs2.getString("art_cod"), rs2.getString("art_descri") + " " + rs2.getString("mar_descri"),
                                            vcant.getText(), rs2.getString("art_preciov"),
                                            String.valueOf(Integer.parseInt(vcant.getText()) * Integer.parseInt(rs2.getString("art_preciov"))), vdep_cod.getSelectedItem().toString()};
                                        modelo.addRow(datosdetalle);
                                        rs2.close();
                                        total_pedido();
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No se encontraron datos coincidentes", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                                vcant.setText("");
                                vcant.requestFocus();
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(pedidoventas.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                        vcant.setText("");
                        vcant.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este campo solo puede tener numeros", "ERROR", JOptionPane.WARNING_MESSAGE);
                    vcant.setText("");
                    vcant.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                vcant.setText("");
                vcant.requestFocus();
            }
            vart_descri.setText("");
            vart_cod.setText("");
            vcant.setText("");
            vdep_cod.requestFocus();
        }
    }//GEN-LAST:event_vcantKeyPressed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(null,"Desea Grabar el pedido de venta?","Atencion",JOptionPane.YES_NO_OPTION);
        if (mensaje == 0) {
            obtener_fecha();
            con.insertar_datos("pedido_cabventa", "ped_cod, ped_fecha, emp_cod, cli_cod, estado", 
                    vped_cod.getText()+", '"+fecha_pedido+"',"+empleado+","+vcli_cod.getText()+",'P'", 0);
            for (int i = 0; i < grilla.getRowCount(); i++) {
                con.insertar_datos("detalle_pedventa", "ped_cod, dep_cod, art_cod, ped_cant, ped_precio", 
                        vped_cod.getText()+", split_part('"+grilla.getValueAt(i, 5)+"','-',1)::integer,"
                        +grilla.getValueAt(i, 0)+","+grilla.getValueAt(i, 2)+","+grilla.getValueAt(i, 3), 1);
            }
            btncancelar.doClick();
        }else{
            btncancelar.doClick();
        }
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        habilitar(1);
        vped_cod.setText("");
        vped_cod.setEnabled(false);
        vcli_cod.setText("");
        vcli_cod.setEnabled(false);
        vcliente.setText("");
        vcliente.setEnabled(false);
        vempleado.setText("");
        vempleado.setEnabled(false);
        vdep_cod.removeAllItems();
        vdep_cod.setEnabled(false);
        vart_cod.setText("");
        vart_cod.setEnabled(false);
        vart_descri.setText("");
        vart_descri.setEnabled(false);
        vcant.setText("");
        vcant.setEnabled(false);
        vtotal.setText("0");
        for (int i = grilla.getRowCount()-1; i >= 0; i--) {
            DefaultTableModel modelo;
            modelo = (DefaultTableModel) grilla.getModel();
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanularActionPerformed
        dispose();
        new gestion_pedidos(null, false).setVisible(true);
    }//GEN-LAST:event_btnanularActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedidoventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedidoventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedidoventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedidoventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pedidoventas dialog = new pedidoventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnanular;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField vart_cod;
    private javax.swing.JTextField vart_descri;
    private javax.swing.JTextField vcant;
    private javax.swing.JTextField vcli_cod;
    private javax.swing.JTextField vcliente;
    private javax.swing.JComboBox<String> vdep_cod;
    private javax.swing.JTextField vempleado;
    private javax.swing.JTextField vped_cod;
    private com.toedter.calendar.JDateChooser vped_fecha;
    private javax.swing.JTextField vtotal;
    // End of variables declaration//GEN-END:variables
}
