/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.VentanaBuscar;
import clases.conectbd;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeferzon
 */
public class proveedor extends javax.swing.JDialog {

    conectbd con;
    ResultSet rs, rs1, rs2;
    int ban = 0;

    /**
     * Creates new form clientes
     */
    public proveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        con = new conectbd();
        con.conectar();
        llenar_grilla();
        pack();
    }

    public void habilitar(int estado) {
        switch (estado) {
            case 0:
                btnagregar.setEnabled(false);
                btneditar.setEnabled(false);
                btneliminar.setEnabled(false);
                btncancelar.setEnabled(true);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(false);
                btnimprimir.setEnabled(false);
                break;
            case 1:
                btnagregar.setEnabled(true);
                btneditar.setEnabled(true);
                btneliminar.setEnabled(true);
                btncancelar.setEnabled(false);
                btngrabar.setEnabled(false);
                btnsalir.setEnabled(true);
                btnimprimir.setEnabled(true);
                break;

        }
    }

    public void llenar_grilla() {
        String campos[] = new String[]{"COD.", "RUC", "RAZON SOCIAL", "DIRECCION", "TELEFONO"};
        DefaultTableModel modelo = new DefaultTableModel(null, campos);
        grillacli.setModel(modelo);
        rs1 = con.listar_datos("select * from proveedor order by prv_cod");
        try {
            while (rs1.next()) {
                String datos[] = new String[]{rs1.getString("prv_cod"), rs1.getString("prv_ruc"), rs1.getString("prv_razonsocial"),
                    rs1.getString("prv_direccion"), rs1.getString("prv_telefono")};
                modelo.addRow(datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static boolean esSoloLetras(String cadena) {
        //Recorremos cada caracter de la cadena y comprobamos si son letras.
        //Para comprobarlo, lo pasamos a mayuscula y consultamos su numero ASCII.
        //Si está fuera del rango 65 - 90, es que NO son letras.
        //Para ser más exactos al tratarse del idioma español, tambien comprobamos
        //el valor 165 equivalente a la Ñ
        for (int i = 0; i < cadena.length(); i++) {

            char caracter = cadena.toUpperCase().charAt(i);

            int valorASCII = (int) caracter;

            if (valorASCII != 165 && (valorASCII < 65 || valorASCII > 90)) {
                return false; //Se ha encontrado un caracter que no es letra
            }
        }

        //Terminado el bucle sin que se haya retornado false, es que todos los caracteres son letras
        return true;

    }

    public static boolean esnumero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btneditar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vprv_ruc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vprv_razonsocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vprv_direccion = new javax.swing.JTextField();
        vprv_telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vprv_cod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillacli = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();

        btneditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Notepad.png"))); // NOI18N
        btneditar1.setText("Editar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana de Proveedor");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("N° RUC:");

        vprv_ruc.setEnabled(false);
        vprv_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vprv_rucKeyPressed(evt);
            }
        });

        jLabel2.setText("Razon S.:");

        vprv_razonsocial.setEnabled(false);
        vprv_razonsocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vprv_razonsocialKeyPressed(evt);
            }
        });

        jLabel4.setText("Direccion:");

        jLabel6.setText("Telefono:");

        vprv_direccion.setEnabled(false);
        vprv_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vprv_direccionKeyPressed(evt);
            }
        });

        vprv_telefono.setEnabled(false);
        vprv_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vprv_telefonoKeyPressed(evt);
            }
        });

        jLabel7.setText("Codigo:");

        vprv_cod.setEnabled(false);
        vprv_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vprv_codActionPerformed(evt);
            }
        });
        vprv_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vprv_codKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vprv_razonsocial, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(vprv_ruc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(vprv_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vprv_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(vprv_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel2)
                        .addComponent(vprv_razonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(vprv_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(vprv_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(vprv_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(vprv_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );

        grillacli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(grillacli);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setToolTipText("");

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/File.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Notepad.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Bin 1 - Empty.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/cancelar1.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/guardar1.png"))); // NOI18N
        btngrabar.setText("Grabar");
        btngrabar.setEnabled(false);
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/exit.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Gris&GlowV1.5 Icon 20-002.png"))); // NOI18N
        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btncancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btngrabar)
                        .addGap(12, 12, 12)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnagregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnagregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngrabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnimprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        habilitar(0);
        ban = 3;
        JTextField[] tfParam = new JTextField[5];
        tfParam[0] = this.vprv_cod;
        tfParam[1] = this.vprv_ruc;
        tfParam[2] = this.vprv_razonsocial;
        tfParam[3] = this.vprv_direccion;
        tfParam[4] = this.vprv_telefono;
        VentanaBuscar buscar = new VentanaBuscar("select prv_cod, prv_ruc,prv_razonsocial,prv_direccion, prv_telefono from proveedor"
                + " where (prv_cod||''||prv_ruc||''||prv_razonsocial||''||prv_direccion||''||prv_telefono) ilike ",
                new String[]{"CODIGO", "RUC_CI", "RAZON SOCIAL", "DIRECCION", "TELEFONO"}, 5, tfParam);

        buscar.setTitle("Buscador clientes");
        buscar.setVisible(true);
        if (ban == 3) {
            int mensaje = JOptionPane.showConfirmDialog(null, "Desea Borrar los datos del proveedor", "Atencion", JOptionPane.YES_NO_OPTION);
            if (mensaje == 0) {
                con.BorrarDatos("proveedor", "prv_cod", vprv_cod.getText());
                btncancelar.doClick();
            } else {
                btncancelar.doClick();
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        habilitar(0);
        ban = 1;
        rs = con.listar_datos("select coalesce(max(prv_cod),0)+1 as ultimo from proveedor");
        try {
            rs.next();
            vprv_cod.setText(rs.getString("ultimo"));
            rs.close();
            vprv_ruc.setEnabled(true);
            vprv_ruc.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int grabacion = JOptionPane.showConfirmDialog(null, "¿Desea grabar los datos?", "Grabar", JOptionPane.YES_NO_OPTION);
        if (grabacion == 0) {
            if (ban == 2) {
                con.actualizar_datos("proveedor", "prv_cod=" + vprv_cod.getText() + ",prv_ruc=" + vprv_ruc.getText() + ",prv_razonsocial='" + vprv_razonsocial.getText()
                        + "',prv_direccion='" + vprv_direccion.getText() + "',prv_telefono ='" + vprv_telefono.getText()
                        + "'", "prv_cod = " + vprv_cod.getText());
                btncancelar.doClick();
            } else {
                con.insertar_datos("proveedor", "prv_cod, prv_ruc, prv_razonsocial,prv_direccion,prv_telefono", vprv_cod.getText() + "," + vprv_ruc.getText() + ",'"
                        + vprv_razonsocial.getText() + "','" + vprv_direccion.getText() + "','" + vprv_telefono.getText() + "'", 0);
                btncancelar.doClick();
            }

        } else {
            btncancelar.doClick();
        }

    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        habilitar(1);
        ban = 0;
        vprv_cod.setText("");
        vprv_cod.setEnabled(false);
        vprv_ruc.setText("");
        vprv_ruc.setEnabled(false);
        vprv_razonsocial.setText("");
        vprv_razonsocial.setEnabled(false);
        vprv_direccion.setText("");
        vprv_direccion.setEnabled(false);
        vprv_telefono.setText("");
        vprv_telefono.setEnabled(false);
        llenar_grilla();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void vprv_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vprv_rucKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {//Se obtiene el evento del teclado
            if (!vprv_ruc.getText().trim().equals("")) {//se valida que el jtextfield no quede vacio}
                //if(Integer.parseInt(vcli_ruc.getText().trim())>0){//Se valida que el valor ingresado sea mayor a cero
                /*boolean ruc;
                ruc = esnumero(vprv_ruc.getText());
                if(ruc){//validamos que el campo contenga solo letras*/
                vprv_razonsocial.setEnabled(true);
                vprv_razonsocial.requestFocus();
                /*}else{
                        JOptionPane.showMessageDialog(null, "Este campo solo puede contener numeros");
                        vprv_ruc.setText("");
                        vprv_ruc.requestFocus();
                        }*/

 /*}else{
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero","Atencion",JOptionPane.INFORMATION_MESSAGE);
                    vcli_ruc.setText("");
                    vcli_ruc.requestFocus();
                }*/
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede quedar vacio", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                vprv_ruc.setText("");
                vprv_ruc.requestFocus();
            }
        } else {

        }
    }//GEN-LAST:event_vprv_rucKeyPressed

    private void vprv_razonsocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vprv_razonsocialKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {//se obtiene el evento de precionar enter para empezar la validacion
            if (!vprv_razonsocial.getText().trim().equals("")) {//se valida que el campo no este vacio
                /*boolean val;
                val = esSoloLetras(vprv_razonsocial.getText());
                if(val==true){//se valida que sean solo letras para el caso de nombre y apellido*/
                vprv_direccion.setEnabled(true);
                vprv_direccion.requestFocus();
                /*}else{
                    JOptionPane.showMessageDialog(null, "Este campo no admite numeros","Atencion", JOptionPane.INFORMATION_MESSAGE);
                    vprv_razonsocial.setText("");
                    vprv_razonsocial.requestFocus();
                    }
                 */
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede quedar vacio", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                vprv_razonsocial.setText("");
                vprv_razonsocial.requestFocus();
            }

        }
    }//GEN-LAST:event_vprv_razonsocialKeyPressed

    private void vprv_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vprv_direccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {//se obtiene el evento del teclado enter
            if (!vprv_direccion.getText().trim().equals("")) {//se valida si el campo esta vacio
                vprv_telefono.setEnabled(true);
                vprv_telefono.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                vprv_direccion.setText("");
                vprv_direccion.requestFocus();
            }

        }
    }//GEN-LAST:event_vprv_direccionKeyPressed

    private void vprv_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vprv_telefonoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {//SE obtiene evento
            if (!vprv_telefono.getText().trim().equals("")) {//Validacion de espacio en blanco
                btngrabar.setEnabled(true);
                btngrabar.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                vprv_telefono.setText("");
                vprv_telefono.requestFocus();
            }

        }
    }//GEN-LAST:event_vprv_telefonoKeyPressed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        habilitar(0);
        ban = 2;
        JTextField[] tfParam = new JTextField[5];
        tfParam[0] = this.vprv_cod;
        tfParam[1] = this.vprv_ruc;
        tfParam[2] = this.vprv_razonsocial;
        tfParam[3] = this.vprv_direccion;
        tfParam[4] = this.vprv_telefono;
        VentanaBuscar buscar = new VentanaBuscar("select prv_cod, prv_ruc,prv_razonsocial,prv_direccion, prv_telefono from proveedor"
                + " where (prv_cod||''||prv_ruc||''||prv_razonsocial||''||prv_direccion||''||prv_telefono) ilike ",
                new String[]{"CODIGO", "RUC_CI", "RAZON SOCIAL", "DIRECCION", "TELEFONO"}, 5, tfParam);

        buscar.setTitle("Buscador clientes");
        buscar.setVisible(true);

        vprv_ruc.setEnabled(true);
        vprv_ruc.requestFocus();
    }//GEN-LAST:event_btneditarActionPerformed

    private void vprv_codKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vprv_codKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!vprv_cod.getText().trim().equals("")) {
                if (Integer.parseInt(vprv_cod.getText().trim()) > 0) {
                    rs2 = con.listar_datos("select * from proveedor where prv_cod =" + vprv_cod.getText());
                    try {
                        if (rs2.isBeforeFirst()) {
                            rs2.next();
                            vprv_ruc.setText(rs2.getString("prv_ruc"));
                            vprv_razonsocial.setText(rs2.getString("prv_razonsocial"));
                            vprv_direccion.setText(rs2.getString("prv_direccion"));
                            vprv_telefono.setText(rs2.getString("prv_telefono"));
                            rs2.close();
                            vprv_ruc.setEnabled(true);
                            vprv_razonsocial.setEnabled(true);
                            vprv_direccion.setEnabled(true);
                            vprv_telefono.setEnabled(true);
                            btngrabar.setEnabled(true);
                            vprv_cod.setEnabled(false);
                            if (ban == 3) {
                                int mensaje = JOptionPane.showConfirmDialog(null, "Desea borrar los datos del campo?", "Atencion", JOptionPane.YES_NO_OPTION);
                                if (mensaje == 0) {
                                    con.BorrarDatos("proveedor", "prv_cod", vprv_cod.getText());
                                    btncancelar.doClick();
                                } else {
                                    btncancelar.doClick();
                                }
                            }/*else{
                                vcli_cod.setEnabled(false);
                                vcar_descri.setEnabled(true);
                                vcar_descri.selectAll();
                                vcar_descri.requestFocus();
                            }*/
                        } else {
                            JOptionPane.showMessageDialog(null, "No se encontraron datos coincidentes", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                            vprv_cod.setText("");
                            vprv_cod.requestFocus();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(proveedor.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Este campo debe ser mayor a cero", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                    vprv_cod.setText("");
                    vprv_cod.requestFocus();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Este campo no puede quedar vacio", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                vprv_cod.setText("");
                vprv_cod.requestFocus();
            }
        }
    }//GEN-LAST:event_vprv_codKeyPressed

    private void vprv_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vprv_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vprv_codActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        con.generarreporte("proveedor");
    }//GEN-LAST:event_btnimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                proveedor dialog = new proveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneditar1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTable grillacli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField vprv_cod;
    private javax.swing.JTextField vprv_direccion;
    private javax.swing.JTextField vprv_razonsocial;
    private javax.swing.JTextField vprv_ruc;
    private javax.swing.JTextField vprv_telefono;
    // End of variables declaration//GEN-END:variables
}
